add_rules("mode.debug", "mode.release")
set_encodings("utf-8")
set_warnings("all")
set_languages("cxx17")

-- 添加一个选项来控制是否编译可选练习题 (66 及之后)
option("enable_optional_exercises")
    set_default(false)
    set_showmenu(true)
    set_description("Enable optional exercises")

target("test")
set_kind("static")
add_defines(string.format("__XMAKE__=\"%s\"", os.scriptdir():gsub("\\", "/")))
add_files("learn/test.cpp")

target("learn")
set_kind("binary")
add_deps("test")
add_files("learn/learn.cpp")

target("summary")
set_kind("binary")
add_deps("test")
add_files("learn/summary.cpp")
